AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Bucket
Resources:
  TopsKeyStoreBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          # All files
          - ExpirationInDays: 30
            Prefix: "*"
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
    DeletionPolicy: Retain
Outputs:
  BucketName:
    Description: Teemops Key Store Bucket
    Value: 
      Fn::Select:
        - '0'
        - Fn::Split:
          - "."
          - Fn::GetAtt:
            - TopsKeyStoreBucket
            - DomainName