version: "3.3"

services:
  mysql:
    build:
      context: .
    platform: "linux/amd64"
    image: mysql:8.0
    restart: always
    volumes:
      - $PWD/data:/var/lib/mysql
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    # expose:
    #   # Opens port 3306 on the container
    #   - '3306'
    environment:
      MYSQL_DATABASE: "teem"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "teem"
      # You can use whatever password you like
      MYSQL_PASSWORD: "project"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "mysql"
volumes:
  db_data: {}
